namespace: garage-storage-controller-system
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Metrics RBAC
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml

# CRD Roles:
# - accesskey_admin_role.yaml
# - accesskey_editor_role.yaml
# - accesskey_viewer_role.yaml
# - bucket_admin_role.yaml
# - bucket_editor_role.yaml
# - bucket_viewer_role.yaml
