apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garage-controller-leader-election
  labels:
    app.kubernetes.io/name: garage-storage-controller
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garage-controller-leader-election
subjects:
- kind: ServiceAccount
  name: garage-controller
  namespace: garage-controller-system
