apiVersion: v1
kind: Namespace
metadata:
  name: garage-controller-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: garage-storage-controller
    app.kubernetes.io/managed-by: kustomize
