apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: garage-controller-rolebinding
  labels:
    app.kubernetes.io/name: garage-storage-controller
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: garage-controller-role
subjects:
- kind: ServiceAccount
  name: garage-controller
  namespace: garage-controller-system
