apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage-controller
  namespace: garage-controller-system
  labels:
    app.kubernetes.io/name: garage-storage-controller
    app.kubernetes.io/managed-by: kustomize
