apiVersion: garage.getclustered.net/v1alpha1
kind: AccessKey
metadata:
  labels:
    app.kubernetes.io/name: garage-storage-controller
    app.kubernetes.io/managed-by: kustomize
  name: accesskey-sample
spec:
  secretName: foo-some-secret
