# Only for reference, generate a valid API token and store it in a secret.
# To generate a random string: api_token=$(openssl rand -base64 32)
apiVersion: v1
kind: Secret
metadata:
  name: garage-api-token
type: Opaque
stringData:
  api-token: "obviously-not-a-key"
