---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/garage.getclustered.net_buckets.yaml
- bases/garage.getclustered.net_accesskeys.yaml
- bases/garage.getclustered.net_accesspolicies.yaml
# +kubebuilder:scaffold:crdkustomizeresource
