name: Build and release image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # This might be too agressive: once a build has failed a commit will never 'recover'
      - name: Check commit status
        run: |
          checks=$(curl -s \
            https://api.github.com/repos/bmarinov/garage-storage-controller/commits/a70becf78a6b386832f384b9ae2605f129af10a2/check-runs \
            | jq -c '.check_runs[] | {name, conclusion}')

          echo "$checks" | while read -r check; do
              name=$(echo "$check" | jq -r .name)
              conclusion=$(echo "$check" | jq -r .conclusion)
              
              if [ "$conclusion" != "success" ]; then
                  echo "Failed build on ${{ github.sha }}"
                  echo "'$name': '$conclusion'"
                  echo "All runs: $checks"
                  exit 1
              fi
          done

      - name: Log in to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --tags --always --dirty)
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build image
        run: make docker-build IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}

      - name: Push with version tag
        run: make docker-push IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}

      - name: Tag and push latest
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }} \
                     ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          make docker-push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
